### ISSUE TITLE
Manage elasticsearch is not reachable with a port

### ISSUE THREAD

**Issue by dingobar** [acryldata/datahub-helm#10]
I ran into an issue with the helm chart, where it defaults to appending `:9200`  (the port) to the elastic URI, although the AWS ElasticSeararch doesn't work that way (it's reached just `https://elastic-host.domain.com`  without the port). This causes the elasticearch init-job to fail,

> 2021/07/22 14:38:55 Waiting for: https://myuser:mypassword@search-mydomain.eu-central-1.es.amazonaws.com:9200

I got past this step by setting it to yaml null, `~`:
```
global:
    elasticsearch:
        port: ~
```

However, gms does not heed the port variable, and continues to use `:9200`.

Is there an env var I can use to force GMS onto another port?

Another heads up is that the same happened when not using the default mysql port, but there I could just change it back to default.

Edit: Solved by using port 443 (TLS) in stead of 9200. I'll see if I can contribute a note to the docs somewhere.

**Comment by shirshanka** [comment]
@dexter-mh-lee : FYI

**Comment by dingobar** [comment]
Found some more info on AWS forums, seems the [native transport protocol is not supported](https://forums.aws.amazon.com/thread.jspa?messageID=681938), thus the rest interface should be used.

@shirshanka Is this perhaps better raised in the main repo?

**Comment by dingobar** [comment]
Solved by using the TLS port instead, 443.
