### ISSUE TITLE
Unable to install the helm charts

### ISSUE THREAD

**Issue by jai2033shankar** [acryldata/datahub-helm#11]
Error I get when I try and install the helm chart:

Error: This command needs 1 argument: chart name

Helm version :

Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}

**Comment by serefacet** [comment]
Which command did you execute? Could you please write the full command?
