### ISSUE TITLE
passing sasl.mechanism and sasl.jaas.config to values not working

### ISSUE THREAD

**Issue by kishore0709** [acryldata/datahub-helm#132]
**Describe the bug**
Iam passing sasl.mechanism and sasl.jaas.config values to springKafkaConfigurationOverrides is not picking by kafka.

**To Reproduce**
Add values in main values.yaml under 
springKafkaConfigurationOverrides:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kishore0709** [comment]
springKafkaConfigurationOverrides:
#    ssl.keystore.location: /mnt/datahub/certs/datahub.linkedin.com.keystore.jks
#    ssl.truststore.location: /mnt/datahub/certs/datahub.linkedin.com.truststore.jks
#    kafkastore.ssl.truststore.location: /mnt/datahub/certs/datahub.linkedin.com.truststore.jks
    security.protocol: SASL_SSL
    sasl.mechanism: "SCRAM-SHA-512"
    sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username=xxxxxxx password="xxxxxxxx"``

**Comment by kishore0709** [comment]
We are using AWS MSK kafka and trying to connect with SASL SCRAM with basic auth

**Comment by DruvaRam** [comment]
@kishore0709 

With which pod/container has this issue?

**Comment by kishore0709** [comment]
for the kafkaSetupJob pod/container.

**Comment by dianadujing** [comment]
I got the same issue when I tried to use my own kafka instead of prerequisites. Any update now?
