### ISSUE TITLE
how to login via ldap configured in jaas.conf

### ISSUE THREAD

**Issue by permitroot** [acryldata/datahub-helm#177]
hi here

I could not find any reference on the process to login via ldap configured in jaas.conf

these are the things i've tried.

I removed the user.prop file from the frontend image(v0.2.87) and added the jaas.conf file. 

jaas.conf 
```
WHZ-Authentication {
    com.sun.security.auth.module.LdapLoginModule required
    userProvider="ldap://{ldap_host}:{ldap_port}"
    authIdentity="cn=${0},ou=members,o=identitymaster"
    java.naming.security.authentication="simple"
    debug="true"
};
```
Then there was a problem that I could connect all ID and password I entered.

I want to allow access only to IDs with ldap privileges.

Any help would be appreciated.

Thanks

**Comment by permitroot** [comment]
the jaas setting was wrong. 
resovled :)

**Comment by permitroot** [comment]
the jaas setting was wrong.
resovled :)

**Comment by vsavinkov** [comment]
@permitroot, could you please elaborate? Which config did you use to resolve the issue?
