### ISSUE TITLE
datahub-elasticsearch-setup-job v0.8.45 job is failed during installation

### ISSUE THREAD

**Issue by Lilian1331** [acryldata/datahub-helm#183]
**Describe the bug**
I tried installing with the latest release version v0.8.45 datahub project; on my GKE,  elasticsearch-setup-job is failing with the error:

**To Reproduce**
I installed using the v0.8.45 version of Helmchart provided by Datahub. by following the guide on https://datahubproject.io/docs/deploy/gcp/

install prerequisites
helm install datahub datahub/datahub

**Screenshots**
![image](https://user-images.githubusercontent.com/23545532/195024308-4ebc96d0-50a6-4a5f-85bd-e001fd60c056.png)

**Comment by qspors** [comment]
Same Error with curl option -k is unknown

**Comment by daha** [comment]
A workaround is to set `globals.elasticsearch.insecure` to ""

I think it is a bug in the create-indeces.sh script in version v0.8.45, but I think it is fixed in v0.9.2 or even some earlier version.

**Comment by szalai1** [comment]
yes, this is issue with datahub.sh, and it's been fixed. closing the issue.
