### ISSUE TITLE
Image Tag not correctly set for DataHub-Ingestion-Cron

### ISSUE THREAD

**Issue by dnks23** [acryldata/datahub-helm#232]
**Describe the bug**
Helm Templating Error when enabling datahub-ingestion-cron-job(s).

**To Reproduce**
Steps to reproduce the behaviour:
Install DataHub using the helm-chart with a cron-job enabled along with the prerequisites. When running `helm upgrade --install ..` it fails with:

`Error: template: datahub/charts/datahub-ingestion-cron/templates/cron.yaml:38:109: executing "datahub/charts/datahub-ingestion-cron/templates/cron.yaml" at <.Values.image.tag>: nil pointer evaluating interface {}.image`

It seems that the image-tag is not set properly by helm.

**Expected behavior**
The command should run successfully without errors.

**Additional context**
DataHub Cron-Job version: v0.9.5
Helm-Chart version: 0.2.129

I get the same error for earlier versions of the helm-chart until v 0.2.120.
Version 0.2.119 is the most recent version of the helm-chart which doesn't produce this error.

**Comment by szalai1** [comment]
Thanks for reporting.
As workaround, you can specify the tag under in the values.yaml.  We will fix this soon.

**Comment by dnks23** [comment]
@szalai1  thanks for the quick reply!
Setting the tag explicitly does not work, resulting in the same error message.
