### ISSUE TITLE
Error: UPGRADE FAILED: post-upgrade hooks failed: timed out waiting for the condition

### ISSUE THREAD

**Issue by taragurung** [acryldata/datahub-helm#234]
**Not able to upgrade to the latest version**
Trying to upgrade to latest version leading to following error :

```
client.go:607: [debug] datahub-datahub-upgrade-job: Jobs active: 1, jobs failed: 3, jobs succeeded: 0
upgrade.go:431: [debug] warning: Upgrade "datahub" failed: post-upgrade hooks failed: timed out waiting for the condition
Error: UPGRADE FAILED: post-upgrade hooks failed: timed out waiting for the condition
helm.go:84: [debug] post-upgrade hooks failed: timed out waiting for the condition
UPGRADE FAILED
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:200
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_amd64.s:1581
make: *** [Makefile:174: deploy-helm] Error 1
```

**To Reproduce**
1. Trying to Upgrade the chart from `0.2.109` to `0.2.130`
2.  helm upgrade the chart

**Expected behavior**
Helm upgraded to latest version of datahub

**Comment by szalai1** [comment]
hey @taragurung, can you check wether the upgrade job finished successfully on your namespace?

**Comment by taragurung** [comment]
@szalai1 No, none of them got finished, all are in error state

```
`***************************
APPLICATION FAILED TO START
***************************

Description:

Field kafkaHealthChecker in com.linkedin.gms.factory.kafka.DataHubKafkaEventProducerFactory required a bean of type 'com.linkedin.metadata.dao.producer.KafkaHealthChecker' that could not be found.

The injection point has the following annotations:
	- @javax.inject.Inject()
	- @javax.inject.Named(value="noCodeUpgrade")


Action:

Consider defining a bean of type 'com.linkedin.metadata.dao.producer.KafkaHealthChecker' in your configuration.`
```

**Comment by szalai1** [comment]
ohh yes, I believe this will be fixed in the next release (this week) and the helm chart will be updated too.

**Comment by andreimcriss** [comment]
Any update on this issue?

**Comment by taragurung** [comment]
With the new upgrade to version `0.2.135` it's resolved. Thanks!

**Comment by prashantsinghthakur** [comment]
We are still facing this issue in 0.2.135 as well [12:33 PM] Prashant Thakur
2023-01-19 19:01:33.262  INFO 1 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: cb1873c1fdf5f5f9
2023-01-19 19:01:33.262  INFO 1 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1674154893259
2023-01-19 19:01:33.357  INFO 1 --- [           main] o.a.k.clients.producer.KafkaProducer     : [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
ERROR LoggingFailureAnalysisReporter
 
***************************
APPLICATION FAILED TO START
***************************
 
Description:
 
Field kafkaHealthChecker in com.linkedin.gms.factory.kafka.DataHubKafkaEventProducerFactory required a bean of type 'com.linkedin.metadata.dao.producer.KafkaHealthChecker' that could not be found.
 
The injection point has the following annotations:
        - @javax.inject.Inject()
        - @javax.inject.Named(value="noCodeUpgrade")
 

Action:
 
Consider defining a bean of type 'com.linkedin.metadata.dao.producer.KafkaHealthChecker' in your configuration.
