### ISSUE TITLE
datahub-postgres-setup 0.9.6.1 image not found

### ISSUE THREAD

**Issue by adamhowardprice** [acryldata/datahub-helm#246]
**Describe the bug**
```
│   Warning  Failed     11s   kubelet            Failed to pull image "acryldata/datahub-postgres-setup:v0.9.6.1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/acryldata/datahub-postgres-setup:v0 │
│ .9.6.1": failed to resolve reference "docker.io/acryldata/datahub-postgres-setup:v0.9.6.1": docker.io/acryldata/datahub-postgres-setup:v0.9.6.1: not found
```

**To Reproduce**
Change Helm version to `v0.9.6.1`,
`terraform apply` works as expected, `datahub-postgres-setup` job fails to pull image

**Expected behavior**
`terraform apply` works as expected, `datahub-postgres-setup` job pulls image and runs normally

**Screenshots**

**Additional context**

**Comment by denihot** [comment]
Same here, had to change acryldata/datahub-postgres-setup image tag to `v0.9.6.1rc4` and it worked.

**Comment by avivco** [comment]
I'm facing a similar issue, but with the following error:
`Failed to pull image "acryldata/datahub-postgres-setup:v0.9.6.1": rpc error: code = Unknown desc = Error response from daemon: manifest for acryldata/datahub-postgres-setup:v0.9.6.1 not found: manifest unknown: manifest unknown`
My helm version was **v0.9.6.1** Moving to **v0.9.6.1rc4** didn't resolve the issue
