### ISSUE TITLE
AUTH_OIDC_BASE_URL not beeing set correctly if ingress disabled

### ISSUE THREAD

**Issue by rathberm** [acryldata/datahub-helm#312]
**Describe the bug**

The variable `AUTH_OIDC_BASE_URL` is set in the frontend container and is needed for setting up SSO. Since Helm Chart Version 0.2.160 the variable is set depending on the [Host URL set in the ingress definition](https://github.com/acryldata/datahub-helm/blob/master/charts/datahub/subcharts/datahub-frontend/templates/deployment.yaml#L192).  If `ingress.enabled: false` is set, the variable is still initialized based on the value of the ingress host, which is [chart-example.local](https://github.com/acryldata/datahub-helm/blob/09a9063443af0d8d56727864dd52b280c11b568a/charts/datahub/subcharts/datahub-frontend/values.yaml#LL63C32-L63C32). Since this placeholder example Ingress host is not even [visibly set in the Values File](https://github.com/acryldata/datahub-helm/blob/master/charts/datahub/values.yaml#L34) but instead only in the values file of the subchart, this behavior is unintuitive and not what I expected.
If you try to set `AUTH_OIDC_BASE_URL` as an [extraEnvs](https://github.com/acryldata/datahub-helm/blob/master/charts/datahub/subcharts/datahub-frontend/values.yaml#L98) variable and `ingress.enabled: false` is set,  its value will always be overwritten by `chart-example.local` on deploy.

I think this behavior could be fixed by using an if clause to only set `AUTH_OIDC_BASE_URL` to the value of `datahub-frontend.ingress.hosts.host` if `ingress.enabled: true`.

I understand that SSO only works if using TLS (so AUTH_OIDC_BASE_URL is mostly only needed in combination with an ingress) and for that you need to set up an ingress. But in our case the ingress was set up manually which led to this problem.

**To Reproduce**
Deploy the datahub chart with `datahub-frontend.ingress.enabled: false`  and `datahub-frontend.ingress.hosts.host` not set.

**Expected behavior**
AUTH_OIDC_BASE_URL is not set or is set to the values of AUTH_OIDC_BASE_URL set in the extraEnvs Part of the values file.

I would be willing to implement this fix, please let me know what you think about it.

**Comment by rathberm** [comment]
This is still a bug in datahub-0.2.175.

**Comment by leszekbulawa** [comment]
This workaround seems to be feasible:
```
    ingress:
      enabled: false
      hosts:
        - host: {{ .Values.domain }}
          paths: []
          redirectPaths: []
```

**Comment by jtv8** [comment]
Still an issue in 1.3.0, was not stale, should not have been closed
