### ISSUE TITLE
Don't impose to create secret

### ISSUE THREAD

**Issue by armandleopold** [acryldata/datahub-helm#34]
Hello, 
You shouldn't impose user to create secrets before installing helm package. It goes against best practices of infrastructure as code where you define all your values in the hlem charts.
For exemple, we use [Hashicorp Vault](https://www.vaultproject.io/) to pull our credentials directly in our values.yaml files before installing the chart.

By imposing us to create a secret file containing our secrets it goes against our policies.

https://github.com/acryldata/datahub-helm/blob/0c69e5fc514589527f682ee0023bb4bc43e561fb/charts/prerequisites/values.yaml#L64

https://github.com/acryldata/datahub-helm/blob/0c69e5fc514589527f682ee0023bb4bc43e561fb/charts/prerequisites/values.yaml#L58

Please removes thoses lines as they can't be overriten.

**Comment by dexter-mh-lee** [comment]
Sorry about the late reply, we added these lines for easy spin up of required components. By uncommenting this, a lot of folks will have to modify values.yaml instead of using it as is. 

You can unset a field by using this approach when installing
--set mysql.existingSecret=null

**Comment by dexter-mh-lee** [comment]
Reference https://banzaicloud.com/blog/creating-helm-charts-part-2/#removing-a-default-key

**Comment by armandleopold** [comment]
Hello Dexter, no you cannot from nested dependency Charts : 
[https://github.com/helm/helm/issues/5184](https://github.com/helm/helm/issues/5184)

**Comment by armandleopold** [comment]
I had to use a hack :
```
      # Bug Fix helm drop default datahub values
      sed -i 's/existingPasswordSecret: neo4j-secrets//' charts/datahub-prerequisites/values.yaml
      sed -i 's/existingSecret: mysql-secrets//' charts/datahub-prerequisites/values.yaml
```
