### ISSUE TITLE
Kafka deployment does not work when enabling kraft

### ISSUE THREAD

**Issue by jan-wacker** [acryldata/datahub-helm#377]
**Describe the bug**
The installation of the helm chart does not work when using `helm-drift detection`.

When using flux v2 and the helm drift detection the helm controller does helm dry run against the cluster. An the used kafka helm chart has an error that, when enabling `kraft` two env variables will be created. This is fixed in kafka helm chart version `22.1.6`

**To Reproduce**

1. use fluxv2 and enable helm drift detection
2. install prerequisites helm chart
3. See the following error

```
failed to diff release against cluster resources: StatefulSet/datahub/prerequisites-kafka dry-run failed: 
failed to create manager for existing fields: 
failed to convert new object (datahub/prerequisites-kafka; apps/v1, Kind=StatefulSet) 
to smd typed: .spec.template.spec.containers[name="kafka"].env: duplicate entries for key [name="KAFKA_ENABLE_KRAFT"]
```

**Additional context**

[fixed here kafka helm chart](https://github.com/bitnami/charts/commit/ec08951858d8c6eecb6d49fc72cd387022fb4054)

**Comment by pedro93** [comment]
Hello @jan-wacker 

To be clear is the fix here to bump our kafka helm chart dependency from `22.1.3` to `22.1.6`?

**Comment by jan-wacker** [comment]
@pedro93 
Yes I haven't tested if there are breaking changes in Kafka causing DataHub to break.

**Comment by jan-wacker** [comment]
Hi @pedro93 

I checked the kafka helm chart releases and these changes were made

https://github.com/bitnami/charts/commit/45b550b3580d4a5ec1af5caad0006baf1f5f854c 
https://github.com/bitnami/charts/commit/8d8d074d6c61d189905015c2797de358811d9d52 
https://github.com/bitnami/charts/commit/ec08951858d8c6eecb6d49fc72cd387022fb4054 

It looks good to me please take a look :)

**Comment by pedro93** [comment]
Looks good to me as well. Feel free to raise a PR for the version bump

**Comment by pedro93** [comment]
Thank you for opening the ticket and making the fix! Closing issue as the PR has been merged.
