### ISSUE TITLE
Data Platform url not working

### ISSUE THREAD

**Issue by gopikaops** [acryldata/datahub-helm#382]
On this page 
https://datahubproject.io/docs/generated/metamodel/entities/dataplatform/
Under Data Platform 
when I click on the list for currently available data platforms 
The url does not work 
https://raw.githubusercontent.com/datahub-project/datahub/master/metadata-service/restli-servlet-impl/src/main/resources/DataPlatformInfo.json

**Comment by sachinsaju** [comment]
This issue is resolved in this [PR](https://github.com/datahub-project/datahub/pull/9137).So the issue can be closed.
