### ISSUE TITLE
Failed to install datahub

### ISSUE THREAD

**Issue by Jean-LouisGillet** [acryldata/datahub-helm#418]
Hello,

I'm trying to deploy DataHub on a Azure Kubernetes cluster.
I'm following these guidelines : https://datahubproject.io/docs/deploy/kubernetes/
But I have an issue when trying to deploy datahub :

![image](https://github.com/acryldata/datahub-helm/assets/132054137/27bd867b-e2b2-4bb3-87e3-200e84898481)

Can you please help me ? I cannot find the reason (this is my first HELM deployment)

Jean-Louis

**Comment by gschuurman** [comment]
Hi @Jean-LouisGillet,
You're best bet would be to check the pods that are running in the cluster by running `kubectl get pods`, can you share the commands you've used to deploy, this gives a great indication where you went wrong.
Another thing is that datahub requires a lot of pre-requisites, this can be done via a pre-requisites helm-chart like this one: https://github.com/acryldata/datahub-helm/tree/master/charts/prerequisites

**Comment by scalvanese452** [comment]
Same issue here.  The prerequisites pods never start.

helm install datahub datahub/datahub-prerequisites

**Comment by gschuurman** [comment]
@scalvanese452 can you share some output like `kubectl get pods` and `kubectl describe pod {PODNAME}` And `kubectl logs {PODNAME}`

**Comment by Jean-LouisGillet** [comment]
@gschuurman the command I used was in my previous post :-)
But, FYI, I managed to solve this issue by setting a higher timeout...
Now, I'm facing other issues, I'm investigating further
