### ISSUE TITLE
Changes to pre-requisites charts affecting correct image pulls (mysql) for arm64?

### ISSUE THREAD

**Issue by erikkvale** [acryldata/datahub-helm#435]
Hello, I have been running:

`helm install prerequisites datahub/datahub-prerequisites` 

Quite frequently over the past few weeks, while I do some testing on an M2 Mac running k8s on minikube. All of a sudden today I am getting a `CrashLoopBackOff` on the ` prerequisites-mysql`pod with the error being: `exec /opt/bitnami/scripts/mysql/entrypoint.sh: exec format error` which generally points to an architecture variance. I looked at all the other architectures of the pre-requisite images being pulled to minikube, all are "arm64" as expected, but mysql is "amd64". That bitnami chart for mysql doesn't look changed in Charts.yaml:

```
  - name: mysql
    version: 9.1.8
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: mysql.enabled
```

but still running into that error, only for that chart/image (https://artifacthub.io/packages/helm/bitnami/mysql/9.1.8).

Has anything changed on the datahub side of these charts that would cause this error with the incorrect image architecture to being pulled (unavailable)? Please advise.

**Comment by darnaut** [comment]
This is an issue with minikube and more recent versions (v4.27+) of Docker on Mac, see https://github.com/kubernetes/minikube/issues/18250
