### ISSUE TITLE
Create Datahub PAT programmatically

### ISSUE THREAD

**Issue by jkeerthi-hbk** [acryldata/datahub-helm#459]
Hi Team,

Is the [given](https://datahubproject.io/docs/api/graphql/token-management/) graphql API the only API currently available to generate a datahub token via API call(programmatically)? I am deploying datahub on a k8s instance and by default, since metadata_service_authentication is true in [helm-chart](https://github.com/acryldata/datahub-helm/blob/89c92c8ac73b4dc371d647216d60dff28cc7c9ae/charts/datahub/values.yaml#L699), the graphql API to create a PAT itself fails with a 401 as in the screenshot.

Kindly let me know the answers to below queries.

1. Is there a way to create a token via API (not via Datahub UI) even if metadata_service_authentication  is set to true?
2. If the only way to create the first Datahub token is via UI, and use that for subsequent API requests, is there any other APIs, or provision from Datahub side to ccreate at least a Basic auth clientId/secret  programmatically and use that for subsequent requests to backend to ingest data, instead of a Bearer token?

I am aware that once `metadata_service_authentication` is set to false in helm chart, and I do a helm upgrade, there is no requirement for authentication, and hence the graphql API gives me a token as response. But I cannot use this as i need to re-enable `metadata_service_authentication` to true and again do helm upgarde, and in turn previous token is no longer valid.

**Comment by jkeerthi-hbk** [comment]
![Uploading Screenshot 2024-04-25 at 11.17.39 AM.png…]()

**Comment by jkeerthi-hbk** [comment]
![Screenshot 2024-04-25 at 11 17 39 AM](https://github.com/acryldata/datahub-helm/assets/142390237/3e1fb27d-6a8f-4603-8f83-2a419dfd511f)

**Comment by collinarnett** [comment]
I am also having this same issue. I would like to run some integration tests and it's quite cumbersome to have to go through the UI to generate a token each time I spin up a test cluster.

**Comment by Balvinder-1995** [comment]
Facing same issue. Please let us know if there's a way to create PAT while spinning up datahub in kubernetes cluster.

**Comment by arturo-opsetmoen-amador** [comment]
Do we have any progress on this issue? We have experienced it for a while now...

**Comment by arturo-opsetmoen-amador** [comment]
People back from holidays? :)

**Comment by darnaut** [comment]
Look for `metadata_service_authentication` options, in particular for `system_client_secret` which is documented as

> The key of a secret containing the internal system secret that is used to communicate with DataHub GMS

Therefore the secret that can be used to make requests to DataHub GMS such as to create a PAT. The requests can be made using the "Basic" HTTP authentication scheme:

```
Authorization: Basic __datahub_system:<system_client_secret>
```
