### ISSUE TITLE
Why is the kafka controller replicaCount set to 0

### ISSUE THREAD

**Issue by fzhan** [acryldata/datahub-helm#469]
It's strange that setting is there if it doesn't allow kafka controller? 
https://github.com/acryldata/datahub-helm/blob/6ec58b3ddc3ff9af60b591aefbe78356b84bebd2/charts/prerequisites/values.yaml#L145

**Comment by darnaut** [comment]
Because Kafka is deployed in broker-only mode. Please refer to [Kafka Chart](https://artifacthub.io/packages/helm/bitnami/kafka) documentation for more details.

**Comment by fzhan** [comment]
@darnaut thank you, now I understand this setting is there for the bitnami chart.
