### ISSUE TITLE
HelmChart release cycle vs Datahub updates

### ISSUE THREAD

**Issue by kzgrzendek** [acryldata/datahub-helm#486]
Hello, 

First of all, I'd like to thank you for the quality of your product - it's awesome!

I have a question regarding the versioning of the Helmchart and its release cycle : 

Datahub v0.13.3 released in May, yet if I look at the `appVersion` tag of the latest HelmChart (0.4.19, released 3 weeks ago), I still see `0.13.2`.

Is it just a bug, and that chart is in fact packaging the 0.13.3 Datahub version? 
More generally, are you guys updating the chart and its components at  every Datahub release, or do expect the users to manually update the versions of the chart's dependencies to keep it updated? 

Thanks! :)

**Comment by Philipp-Hillen-SG** [comment]
Was there any reaction through some other channel on this?

**Comment by pedro93** [comment]
Hello,

DataHub releases usually include both the application code + helm chart releases. 

When we don't do helm chart releases it is usually because just bumping the [version](https://github.com/acryldata/datahub-helm/blob/c8d01c4336c3f80f67e3af8a214bb7006a2dae7a/charts/datahub/values.yaml#L676) of DataHub to match the application release version is sufficient.

**Comment by kzgrzendek** [comment]
@pedro93 thanks for your reply :)

That's a shame because it prevents an easy management of the application's life cycle in production (since it forces users to pull the helm chart and manually bump the dependencies' versions instead of just fetching the latest chart version from the repository and update it with dedicated tools like argocd/updatecli/etc).

It's also quite error-prone imo given the number of dependencies.

Is there any plans for a github action or something else that would auto publish the latest chart's version?

Thanks!

**Comment by pedro93** [comment]
Not to my knowledge maybe @david-leifker is able to answer

**Comment by darnaut** [comment]
@kzgrzendek just to make sure we are on the same page here, are you aware that all it takes is to bump the `.datahub.version` option? e.g. via your Helm values file or simply as a Helm option https://github.com/acryldata/datahub-helm/blob/c8d01c4336c3f80f67e3af8a214bb7006a2dae7a/charts/datahub/values.yaml#L676

**Comment by kzgrzendek** [comment]
Hey @darnaut, thanks for your feedback!

I haven't dig enough to find that parameter, that should indeed answer my question. Just to check, is it documented somewhere besides the values.yaml definition? I think that solves a critical concern, and as the update mechanism differs a bit from the conventional helm chart version update, it would be great to have a little update section somewhere in the docs imo. 

I'm gonna close that question, thank you
