### ISSUE TITLE
Add PostgreSQL as alternative to MySQL in prerequisites

### ISSUE THREAD

**Issue by mihaitodor** [acryldata/datahub-helm#49]
I'd like to be able to deploy the PostgreSQL [subchart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) instead of the MySQL one as part of the prerequisites chart, since DataHub also supports it as a backend store. I believe this also requires running the [postgres-setup](https://github.com/linkedin/datahub/tree/48b3d7afa0ee4442cb4d1bd228839cf6becfc452/docker/postgres-setup) container instead of the [MySQL one](https://github.com/acryldata/datahub-helm/blob/ce4fd3d0a10a1587ec8d0bb94ffec2bcd0270973/charts/datahub/templates/mysql-setup-job.yml).

**Comment by anshbansal** [comment]
PR has been merged. Closing.
