### ISSUE TITLE
Support JAAS frontend authentication configuration

### ISSUE THREAD

**Issue by claudio-benfatto** [acryldata/datahub-helm#51]
Hi here,

**Is your feature request related to a problem? Please describe.**
It would be nice that configuring the jaas authentication method for the frontend, as described in [datahub frontend authentication](https://datahubproject.io/docs/datahub-frontend#authentication) could be natively supported by the helm charts

**Describe the solution you'd like**
Ideally the content of the [jaas.conf](https://github.com/linkedin/datahub/blob/master/datahub-frontend/conf/jaas.conf) and maybe of the `/datahub-frontend/conf/user.props` there referred, could be easily configurable by passing the content to a value (property) of the frontend subchart

**Describe alternatives you've considered**
If there is a way to achieve this without modifying the existing chart please let me know ;)

Thanks!

**Comment by snowsky** [comment]
It seems this is not complete, also looking for a way to set up Jaas in Helm Chart. 👍
