### ISSUE TITLE
Error: secret "datahub-encryption-secrets" not found

### ISSUE THREAD

**Issue by qspors** [acryldata/datahub-helm#90]
Hello.
In cause of if I will kill existing pod with gms, next pod cannot to start cuz generated secret "datahub-encryption-secrets" is not exist. I got this error:
_Error: secret "datahub-encryption-secrets" not found_
This is temporary secret.
Looks like I need to full redeployment of app for get new encryption secret.
Also I saw this option "global.datahub.encryptionKey.secretRef"
but I cant understood what requirements and form of this.
Could you explain how right to use this option for avoid issues with temporary generated secrets.
Thank you.

**Comment by allenhaozi** [comment]
I got same error

and I add the following command fix it

```shell
kubectl create secret generic datahub-encryption-secrets --from-literal=encryption_key_secret=datahub
```

`Name:         datahub-datahub-gms-c55c74d8c-6djph
Namespace:    datahub
Priority:     0
Node:         openaios-dev-k8s-6/172.27.70.36
Start Time:   Mon, 07 Mar 2022 17:30:19 +0800
Labels:       app.kubernetes.io/instance=datahub
              app.kubernetes.io/name=datahub-gms
              pod-template-hash=c55c74d8c
Annotations:  cni.projectcalico.org/podIP: 10.42.10.132/32
              cni.projectcalico.org/podIPs: 10.42.10.132/32
Status:       Pending
IP:           10.42.10.132
IPs:
  IP:           10.42.10.132
Controlled By:  ReplicaSet/datahub-datahub-gms-c55c74d8c
Containers:
  datahub-gms:
    Container ID:   
    Image:          linkedin/datahub-gms:v0.8.27
    Image ID:       
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:http/health delay=60s timeout=1s period=30s #success=1 #failure=8
    Readiness:      http-get http://:http/health delay=60s timeout=1s period=30s #success=1 #failure=8
    Environment:
      MCE_CONSUMER_ENABLED:              true
      MAE_CONSUMER_ENABLED:              true
      ENTITY_REGISTRY_CONFIG_PATH:       /datahub/datahub-gms/resources/entity-registry.yml
      DATAHUB_ANALYTICS_ENABLED:         true
      EBEAN_DATASOURCE_USERNAME:         root
      EBEAN_DATASOURCE_PASSWORD:         <set to the key 'mysql-root-password' in secret 'mysql-secrets'>  Optional: false
      EBEAN_DATASOURCE_HOST:             prerequisites-mysql:3306
      EBEAN_DATASOURCE_URL:              jdbc:mysql://prerequisites-mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
      EBEAN_DATASOURCE_DRIVER:           com.mysql.cj.jdbc.Driver
      KAFKA_BOOTSTRAP_SERVER:            prerequisites-kafka:9092
      KAFKA_SCHEMAREGISTRY_URL:          http://prerequisites-cp-schema-registry:8081
      ELASTICSEARCH_HOST:                elasticsearch-master
      ELASTICSEARCH_PORT:                9200
      GRAPH_SERVICE_IMPL:                neo4j
      NEO4J_HOST:                        prerequisites-neo4j-community:7474
      NEO4J_URI:                         bolt://prerequisites-neo4j-community
      NEO4J_USERNAME:                    neo4j
      NEO4J_PASSWORD:                    <set to the key 'neo4j-password' in secret 'neo4j-secrets'>  Optional: false
      UI_INGESTION_ENABLED:              true
      SECRET_SERVICE_ENCRYPTION_KEY:     <set to the key 'encryption_key_secret' in secret 'datahub-encryption-secrets'>  Optional: false
      UI_INGESTION_DEFAULT_CLI_VERSION:  0.8.26.6
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from datahub-datahub-gms-token-2gmnp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  datahub-datahub-gms-token-2gmnp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  datahub-datahub-gms-token-2gmnp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason  Age                     From     Message
  ----     ------  ----                    ----     -------
  Normal   Pulled  7m52s (x5283 over 19h)  kubelet  Container image "linkedin/datahub-gms:v0.8.27" already present on machine
  Warning  Failed  2m56s (x5307 over 19h)  kubelet  Error: secret "datahub-encryption-secrets" not found`

**Comment by daha** [comment]
I had the same issue today when I was trying to update and I think I know what is wrong with the generation of the secret (when global.datahub.encryptionKey.provisionSecret=true).

On the first install of the helm chart the secret will be created (when global.datahub.encryptionKey.provisionSecret=true) and everything is find. The problem then running some kind of update is the guard around the secret:

``` 
{{- $secret := lookup "v1" "Secret" .Release.Namespace "datahub-encryption-secrets" -}}
{{- if (and (not $secret) (.Values.global.datahub.encryptionKey.provisionSecret)) -}}
...
{{- end -}}
```

If the secret exist (from the first install) it will remove the block with the secret since `(not $secret)` will then be false and helm will delete the secret and the pods will fail to start as the secret does not exist, and the helm upgrade will typically rollback and the secret will be added from the previous install again.

**Comment by jjoyce0510** [comment]
Thanks for the reports folks. I think the analysis from @daha is spot on. We didn't foresee the issue about clearing the secret value when this block is omitted. We'll need to do something like https://stackoverflow.com/questions/56170052/how-not-to-overwrite-randomly-generated-secrets-in-helm-templates to address it. 

For now, another option is to disable auto-provisioning of this secret, which serves a key with which to encrypt ingestion secrets. To do so, you can set provisionSecret to false and provide an override for the secret reference (name, value).

Will provide updates on a fix as we have them!
John

**Comment by Babbleshack** [comment]
HI I am still experience this issue. Is there a workaround?
